### ISSUE TITLE
Release Plans

### ISSUE THREAD

**Issue by NyanKiyoshi** [NyanKiyoshi/pytest-django-queries#5]
## 0.1.0
- [x] The plugin is now able to support multiple pytest sessions without conflicting (#1)
- [x] The plugin non-longer benchmarks everything but instead, the user is charged to manually flag each test as to be or not to be benchmarked (#1).

## 1.0.0.dev1 (12 May 2019)
- [x] Add the cli with the `show` and `html` options (#3)

## 1.0.0a1 (13 May 2019)
- [x] Add option to customize the output file, e.g. `--queries-report=path` (#10 -> #13)

## 1.0.0a2 (16 May 2019)
- [x] Freeze weak requirements that may break the tests
- [x] Add RTD documentation (#7)
- [x] Add changelog file and entries + a release guide (#6)
- [x] Fix #15
- [x] Move the HTML template into a single file (#18)

## 1.0.0b1 (19 May 2019)
- [x] Raw Diff tool (#22)
  - [x] Term Colors (#22)

## 1.0.0rc1 (27 May 2019)
- [x] Switch to black (#8)
- [x] Enforce flake8 (#8)
- [x] Add possibility to backup results (#24)
- [x] Add possibility to save HTML without being dependent on any platform (#27)

## 1.0.0rc2 (5 June 2019)
- [x] Add help text for parameters in cli (#28)
- [x] Add `backup` command in cli to make it faster to backup (#29)
- [x] Remove test prefix from dotted import strings (#34)
- [x] Add note to documentation on how to run tests separately (#23)
- [x] Fix issues with fixtures and django plugins (#35)

## 1.0.0rc3 (6 June 2019)
- [x] Add support for `pytest-xdist` (multi-workers tests - #36)

## 1.0.0 (7 June 2019)
Should be release as rc3 is. If everything goes correctly.

## 1.1.0 (TBA)
- Change in the HTML template: generate sums of queries (#12)
- Generate a more compact table (#11) - as a `export` command (aliased to `show --compact`).
